# Generated by Django 5.0.4 on 2024-05-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_txt',
            new_name='choice_text',
        ),
    ]
